package com.mym.webapp.Dao;

// default package
// Generated 24-nov-2015 22:24:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.sql.rowset.spi.TransactionalWriter;

import org.zkoss.zk.ui.Session;
import org.zkoss.zkplus.hibernate.HibernateUtil;

/**
 * Propiedades generated by hbm2java
 */
public class Propiedades implements java.io.Serializable {

	private BigDecimal idpropiedad;
	private String categoria;
	private double precio;
	private String descripcion;
	private Date fechaingreso;
	private boolean activo;
	private String direccion;

	public Propiedades() {
	}

	public Propiedades(BigDecimal idpropiedad, String categoria, double precio, String descripcion, Date fechaingreso,
			boolean activo, String direccion) {
		this.idpropiedad = idpropiedad;
		this.categoria = categoria;
		this.precio = precio;
		this.descripcion = descripcion;
		this.fechaingreso = fechaingreso;
		this.activo = activo;
		this.direccion = direccion;
	}

	public BigDecimal getIdpropiedad() {
		return this.idpropiedad;
	}

	public void setIdpropiedad(BigDecimal idpropiedad) {
		this.idpropiedad = idpropiedad;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	
//	//insertar con hibernate 
//	public void insertarPropiedad(BigDecimal idpropiedad, String categoria, double precio, String descripcion,
//			Date fechaingreso, boolean activo, String direccion) {
//		Session session = HibernateUtil.getSessionFactory().Opensesion();
//		TransactionalWriter tx = null;
//		
//		Propiedades propiedades = new Propiedades();
//		propiedades.setIdpropiedad(idpropiedad);
//		propiedades.setCategoria(categoria);
//		propiedades.setPrecio(precio);
//		propiedades.setDescripcion(descripcion);
//		propiedades.setFechaingreso(fechaingreso);
//		propiedades.setActivo(activo);
//		propiedades.setDireccion(direccion);
//
//		try {
//			tx = session.beginTransaccion();
//			session.save(propiedades);
//			tx.commit();
//
//		} catch (HibernateException e) {
//			if (tx != null) {
//				tx.rollback();
//			}
//		}
//		throw new RuntimeException(e);
//	}final
//
//	{
//		session.close();
//
//	}

}
